---
   - name: download Android NDK
     get_url: dest={{ ansible_cache_dir }} url=https://www.crystax.net/download/{{ android_ndk_zipfile }} validate_certs=no timeout=3000
     sudo: yes

   - name: unpack Android NDK
     unarchive: copy=no src={{ ansible_cache_dir }}/{{ android_ndk_zipfile }} dest=/opt/android creates=/opt/android/{{ android_ndk_folder }}
     sudo: yes 

   - name: chown files
     file: path=/opt/android/{{ android_ndk_folder }} recurse=yes state=directory 

   - name: add ANDROID_NDK_HOME
     action: lineinfile dest=/home/vagrant/.bashrc line="{{ item }}"
     with_items:
        - 'export ANDROID_NDK=/opt/android/{{ android_ndk_folder }}'

        - 'export PATH=$PATH:$ANDROID_NDK'
     sudo: no

