---
   - name: download Android NDK
     get_url: dest={{ ansible_cache_dir }} url=https://www.crystax.net/download/{{ android_ndk_zipfile }} timeout=3000
     sudo: yes

   - name: unpack Android NDK
     unarchive: copy=no src={{ ansible_cache_dir }}/{{ android_ndk_zipfile }} dest=/opt/android creates=/opt/android/{{ android_ndk_folder }}
     sudo: yes 

   - name: chown files
     file: path=/opt/android/{{ android_ndk_folder }} recurse=yes state=directory 
