---

   - name: unpack file
     unarchive: src=../files/libjpeg-turbo-1.4.90.tar.gz dest=/opt/waid/android/WAID/app/src/main/jni  

   - name: chown files
     file: path=/opt/waid/android/WAID/app/src/main/jni/{{jpeg_turbo}} recurse=yes state=directory
