 - name: download opencv
   get_url: url=http://downloads.sourceforge.net/project/opencvlibrary/opencv-android/2.4.9/OpenCV-2.4.9-android-sdk.zip dest=/opt/ansible_cache

 - name: unpack opencv
   unarchive: src=/opt/ansible_cache/OpenCV-2.4.9-android-sdk.zip dest=/opt/android copy=no

 - name: chown files
   file: path=/opt/android/{{ opencv_sdk_folder }} recurse=yes state=directory group=vagrant owner=vagrant
